version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

orbs:
  percy: percy/agent@0.1.2

jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - run:
          name: Create GitHub Deployment
          command: ./tasks/deployment/start.sh > deployment
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run:
          name: Installing Dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build Components
          command: yarn build
      - run:
          name: Build Storybook
          command: yarn build-storybook
      - store_artifacts:
          path: storybook-static
      - save_cache:
          paths:
            - ./node_modules/
          key: cache-{{ checksum "package.json" }}
      - run:
          name: Add GitHub Deployment success status
          command: ./tasks/deployment/end.sh success
          when: on_success
      - run:
          name: Add GitHub Deployment error status
          command: ./tasks/deployment/end.sh error
          when: on_fail
  run_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.7.0
    parallelism: 3
    steps:
      - attach_workspace:
          at: .
      - run: echo "your tests run here"

workflows:
  deploy:
    jobs:
      - deploy
  test:
    jobs:
      - run_tests
      - percy/finalize_all:
          requires:
            - run_tests
