version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.cache }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-{{ .Environment.cache }}-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ .Environment.cache }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - cache-
      - run:
          name: Build components storybook
          command: |
            yarn build
            yarn build-storybook
      - store_artifacts:
          path: storybook-static
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static
      - run: ./tasks/add-deployment.js

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
