version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create GitHub Deployment
          command: ./tasks/deployment/start.sh > deployment
      - restore_cache:
          keys:
            - cache-{{ .Environment.cache }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-{{ .Environment.cache }}-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build Components
          command: yarn build
      - run:
          name: Build Storybook
          command: yarn build-storybook
      - store_artifacts:
          path: storybook-static
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ .Environment.cache }}-{{ checksum "package.json" }}
      - run:
          name: Add GitHub Deployment success status
          command: ./tasks/deployment/end-with-success.sh
          when: on_success
      - run:
          name: Add GitHub Deployment error status
          command: ./tasks/deployment/end-with-error.sh
          when: on_fail

workflows:
  deploy:
    jobs:
      - deploy
