version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.7.0

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.cache }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-{{ .Environment.cache }}-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - run: ./tasks/deployment/start.js > deployment
      - run:
          name: Build Components
          command: yarn build
      - run:
          name: Build Storybook
          command: yarn build-storybook
      - store_artifacts:
          path: storybook-static
      - run: |
          ./tasks/deployment/end.js <<< echo "$(cat deployment)"
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ .Environment.cache }}-{{ checksum "package.json" }}

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
